/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doacaosangue.DoacaoGUI;

import doacaosangue.MedicoGUI.MedicoroomJFrame;
import doacaosangue.doacao.Doacao;
import doacaosangue.doacao.DoacaoNegocio;
import doacaosangue.doador.Doador;
import doacaosangue.doador.DoadorDAO;
import doacaosangue.doador.DoadorNegocio;
import doacaosangue.medico.Medico;
import doacaosangue.medico.MedicoNegocio;
import doacaosangue.receptor.Receptor;
import doacaosangue.receptor.ReceptorDAO;
import doacaosangue.receptor.ReceptorNegocio;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author semnome
 */
public class DoacaoRoomJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DoacaoRoomJFrame
     */
    public DoacaoRoomJFrame() {
        initComponents();
    }

    public String geraDataDoacao() {
        Calendar calendar = Calendar.getInstance();
        int ano = calendar.get(Calendar.YEAR);
        int mes = calendar.get(Calendar.MONTH);
        int dia = calendar.get(Calendar.DAY_OF_MONTH);
        String dia1 = Integer.toString(dia);
        String mes1 = Integer.toString(mes + 1);
        String ano1 = Integer.toString(ano);
        String data = dia1 + "/" + mes1 + "/" + ano1;
        return data;
    }

    public Boolean autorizarDoacao(String cpf_doador, String cpf_receptor) throws Exception {
        boolean log = false;
        String query = "select tipo_sangue from doador where cpf_doador = " + "'" + cpf_doador + "'";
        DoadorDAO dd = new DoadorDAO();
        ResultSet rsd = dd.conectar().executeQuery(query);
        rsd.next();
        dd.desconectar();
        //String sangue = rsd.getNString(1);
        String query1 = "select tipo_sangue from receptor where cpf_receptor = " + "'" + cpf_receptor + "'";
        ReceptorDAO rd = new ReceptorDAO();
        ResultSet rsr = rd.conectar().executeQuery(query1);
        rsr.next();
        rd.desconectar();
        if (rsd.getString("tipo_sangue").equals("A+") && rsr.getString("tipo_sangue").equals("A+") || rsr.getString("tipo_sangue").equals("AB+")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("A-") && rsr.getString("tipo_sangue").equals("A+") || rsr.getString("tipo_sangue").equals("A-") || rsr.getString(1).equals("AB+") || rsr.getString("tipo_sangue").equals("AB-")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("B+") && rsr.getString("tipo_sangue").equals("B+") || rsr.getString("tipo_sangue").equals("AB+")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("B-") && rsr.getString("tipo_sangue").equals("B+") || rsr.getString("tipo_sangue").equals("B-") || rsr.getString("tipo_sangue").equals("AB+") || rsr.getString("tipo_sangue").equals("AB-")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("AB+") && rsr.getString("tipo_sangue").equals("AB+")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("AB-") && rsr.getString("tipo_sangue").equals("AB+") || rsr.getString("tipo_sangue").equals("AB-")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("O+") && rsr.getString("tipo_sangue").equals("A+") || rsr.getString("tipo_sangue").equals("B+") || rsr.getString("tipo_sangue").equals("O+") || rsr.getString("tipo_sangue").equals("AB+")) {
            log = true;
        } else if (rsd.getString("tipo_sangue").equals("O-")) {
            log = true;
        }
        return log;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF Doador");

        jLabel2.setText("CPF Receptor");

        jButton2.setText("Doações");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("CRM Médico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addGap(197, 197, 197)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Doador dd = new Doador();
        DoadorNegocio ddn = new DoadorNegocio();
        dd.setCpf_doador(jTextField1.getText());
        Receptor r = new Receptor();
        ReceptorNegocio rn = new ReceptorNegocio();
        r.setCpf_receptor(jTextField2.getText());
        Medico m = new Medico();
        MedicoNegocio mn = new MedicoNegocio();
        m.setCrm(jTextField3.getText());
        Doacao d = new Doacao();
        d.setDt_doacao(this.geraDataDoacao());
        d.setDoador(dd);
        d.setMedico(m);
        d.setReceptor(r);
        DoacaoNegocio dn = new DoacaoNegocio();
        try {
            if (ddn.loginDoador(dd.getCpf_doador()) == true) {
                JOptionPane.showMessageDialog(null, "Doador não existente ou incorreto");
                jTextField1.grabFocus();
            } else if (rn.loginReceptor(r.getCpf_receptor()) == true) {
                JOptionPane.showMessageDialog(null, "Receptor não existente ou incorreto");
                jTextField2.grabFocus();
            } else if (mn.loginMedico(m.getCrm()) == true) {
                JOptionPane.showMessageDialog(null, "Medico não existente ou incorreto");
                jTextField3.grabFocus();
            } else {
                try {
                    if (autorizarDoacao(jTextField1.getText(), jTextField2.getText()) == true) {
                        dn.cadastrarDoacao(d);
                        JOptionPane.showMessageDialog(null, "Doou");
                    } else {
                        JOptionPane.showMessageDialog(null, "Tipos de sangue imcompativeis");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(DoacaoRoomJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DoacaoConsultarJFrame login = new DoacaoConsultarJFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MedicoroomJFrame login = new MedicoroomJFrame();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoacaoRoomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoacaoRoomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoacaoRoomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoacaoRoomJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoacaoRoomJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
